version: "3.7"
services: 
    ubuntu:
        container_name: ubuntu
        image: 'zjzstu/ubuntu:latest'
        build: .
        environment: 
            - XMODIFIERS="@im=fcitx"
            - QT_IM_MODULE="fcitx"
            - GTK_IM_MODULE="fcitx"
        tty: true
        stdin_open: true
        volumes: 
            - "home:/var/uhome"
volumes: 
    home: