version:  "3"
services:
    nginx:
        container_name: nginx
        image: nginx
        ports:
            - "80:80"
        volumes: 
            - "~/nginx/www:/opt/www"
            - "~/nginx/logs:/var/log/nginx"
            - "~/nginx/conf.d:/etc/nginx/conf.d"
            - "~/nginx/nginx.conf:/etc/nginx/nginx.conf"
        restart: always
