version: "3.7"
services: 
    jenkins:
        labels:
            AUTHOR: "zhujian <zjzstu@github.com>"
        container_name: jenkins
        image: jenkins/jenkins
        volumes: 
            - "jenkins_home:/var/jenkins_home"
        ports: 
            - "7070:8080"
            - "50000:50000"
        restart: always
        tty: true
        stdin_open: true
    gitlab:
        labels:
            AUTHOR: "zhujian <zjzstu@github.com>"
        container_name: gitlab
        image: gitlab/gitlab-ce:latest
        volumes: 
            - "/srv/gitlab/config:/etc/gitlab"
            - "/srv/gitlab/logs:/var/log/gitlab"
            - "/srv/gitlab/data:/var/opt/gitlab"
        ports: 
            - "7010:7010"
            - "7020:22"
        restart: always
        tty: true
        stdin_open: true
volumes: 
    jenkins_home:
        external: true